<template>
  <PublicLegalLayout
    eyebrow="DISCLAIMER"
    title="Health and AI Disclaimer"
    intro="Fitness AI Planner provides planning, educational, and informational guidance only. This page explains the limits of that guidance, the risks of relying on AI-generated outputs, and when qualified professional support is more appropriate."
    last-updated="April 14, 2026"
  >
    <section>
      <h2>Informational use only</h2>
      <p>
        Fitness AI Planner provides planning, educational, and informational guidance only. It
        does not provide medical diagnosis, treatment, prescription advice, emergency support,
        or licensed professional supervision.
      </p>
      <p>
        Nothing shown in the service should be treated as a substitute for advice from a
        qualified physician, registered dietitian, physical therapist, psychologist, or other
        licensed professional who knows your personal circumstances.
      </p>
    </section>

    <section>
      <h2>Not intended for emergency use</h2>
      <p>
        Fitness AI Planner is not intended for emergency use. If you think you may be having a
        medical emergency, severe injury, acute mental-health crisis, or other urgent safety
        issue, contact emergency services or an appropriate urgent-care provider immediately
        instead of relying on the app.
      </p>
    </section>

    <section>
      <h2>Training and nutrition recommendations may not fit every person</h2>
      <p>
        Suggestions are generated from user-provided data, logged history, and system analysis.
        They may not be appropriate for every individual, training background, injury history,
        medical condition, medication use, pregnancy status, age, disability, eating-disorder
        concern, dietary restriction, or recovery need.
      </p>
      <p>
        You should adapt recommendations based on your own condition, context, and any advice
        you receive from qualified professionals. If you have any doubt about whether a
        training or nutrition suggestion is safe for you, do not rely on the app alone.
      </p>
    </section>

    <section>
      <h2>Seek professional help when appropriate</h2>
      <p>
        If you have an injury, chronic condition, eating-disorder concern, pregnancy-related
        concern, unexplained symptoms, pain, dizziness, chest discomfort, unusual fatigue, or
        any other health issue, consult a qualified clinician or specialist before acting on
        any recommendation shown in the service.
      </p>
    </section>

    <section>
      <h2>AI limitations and no guarantee of suitability</h2>
      <p>
        AI-generated outputs may be incomplete, outdated, inconsistent, or mistaken. They may
        reflect limitations in models, prompts, data quality, or logged history. They should
        not be treated as the sole basis for important health, recovery, nutrition, or
        exercise decisions.
      </p>
      <p>
        Fitness AI Planner does not guarantee that any recommendation, summary, or suggested
        plan is safe, effective, accurate, or suitable for your specific situation.
      </p>
    </section>

    <section>
      <h2>User responsibility and assumption of risk</h2>
      <p>
        You remain responsible for how you train, eat, recover, interpret the information
        shown by Fitness AI Planner, and act on any recommendation or summary generated by the
        service. Exercise, diet change, recovery interventions, and body-composition goals can
        involve risk, and outcomes vary by person.
      </p>
    </section>

    <section>
      <h2>Contact and questions</h2>
      <p>
        For questions about this disclaimer, risk-related wording, or general support issues,
        contact:
        <strong>13957075669@139.com</strong>
      </p>
    </section>
  </PublicLegalLayout>
</template>

<script setup>
import PublicLegalLayout from '@/components/public/PublicLegalLayout.vue'
</script>
